/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonSetting: typeof import('./src/components/Setting/ButtonSetting/index.vue')['default']
    ButtonWidget: typeof import('./src/components/Widget/ButtonWidget/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    LinkSetting: typeof import('./src/components/Setting/LinkSetting/index.vue')['default']
    LinkWidget: typeof import('./src/components/Widget/LinkWidget/index.vue')['default']
    RenderPanel: typeof import('./src/components/RenderPanel.vue')['default']
    SettingPanel: typeof import('./src/components/SettingPanel.vue')['default']
    WidgetFrame: typeof import('./src/components/Widget/WidgetFrame/index.vue')['default']
    WidgetPanel: typeof import('./src/components/WidgetPanel.vue')['default']
  }
}
